name: math-and-machine-learning
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _openmp_mutex=4.5=5_kmp_llvm
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - chess=1.11.0=pyhd8ed1ab_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - cpython=3.8.20=py38hd8ed1ab_2
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - fsspec=2024.10.0=pyhff2d567_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - gymnasium=0.29.1=py38hb563948_1
  - icu=75.1=he02047a_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - jax-jumpy=1.0.0=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libabseil=20240116.2=cxx17_he02047a_1
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libprotobuf=4.25.3=hd5b35b9_1
  - libsqlite=3.50.4=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtorch=2.4.0=cpu_mkl_h85b1651_101
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.4=h4922eb0_0
  - markupsafe=2.1.5=py38h01eb140_0
  - mkl=2023.2.0=ha770c72_50498
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.24.4=py38h59b608b_0
  - openssl=3.5.4=h26f9b46_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - python_abi=3.8=8_cp38
  - pytorch=2.4.0=cpu_mkl_py38ha4c0195_101
  - readline=8.2=h8c095d6_2
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sleef=3.9.0=ha0421bc_0
  - sympy=1.13.3=pyh2585a3b_104
  - tbb=2021.13.0=hb60516a_3
  - tk=8.6.13=noxft_hd72426e_102
  - typing_extensions=4.12.2=pyha770c72_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zipp=3.21.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - pandas==2.0.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - tqdm==4.67.1
      - tzdata==2025.2
prefix: /home/iaquobe/.conda/envs/math-and-machine-learning
