name: chess_ml
channels:
  - pytorch
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=6_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - chess=1.11.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.12.12=py312hd8ed1ab_1
  - cuda-cudart=12.4.127=he02047a_2
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-nvrtc=12.4.127=he02047a_2
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-opencl=12.4.127=he02047a_1
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - filelock=3.20.0=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312hcaba1f9_2
  - icu=75.1=he02047a_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.5.8=he02047a_2
  - libcufft=11.2.1.3=he02047a_2
  - libcufile=1.9.1.3=he02047a_2
  - libcurand=10.3.5.147=he02047a_2
  - libcusolver=11.6.1.9=he02047a_2
  - libcusparse=12.3.1.170=he02047a_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnpp=12.2.5.30=he02047a_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.4.127=he02047a_2
  - libnvjitlink=12.4.127=he02047a_2
  - libnvjpeg=12.3.1.117=he02047a_2
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6=pyhcf101f3_0
  - numpy=2.3.5=py312h33ff503_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.3=py312hf79963d_1
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=h8d10470_4
  - tk=8.6.13=noxft_ha0e22de_103
  - torchtriton=3.1.0=py312
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/iaquobe/.conda/envs/chess_ml
