site_name: My Docs



plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options: 
          show_submodules: true
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          # show_if_no_docstring: true
          show_source: false
          show_root_members_full_path: true
          show_object_full_path: true
          members_order: source
          merge_init_into_class: true
          docstring_section_style: list
          show_signature_type_parameters: true
          show_signature_annotations: true
          parameter_headings: false
          backlinks: true
          heading_level: 2


theme: 
  name: "material"
