site_name: My Docs



plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options: 
          show_submodules: true
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          show_source: false
          merge_init_into_class: true
          docstring_section_style: list
          show_signature_type_parameters: true
          show_signature_annotations: true
          parameter_headings: false
          show_root_toc_entry: false
          backlinks: true


theme: 
  name: "material"

nav:
  - Home: index.md
  - API: 
    - Models: api/model.md
    - Env: api/env.md
    - Train: api/train.md
    - Data: api/data.md
